spring:
  redis:
    pool:
      min-idle: 0
      max-idle: 10
      max-active: 20
      max-wait: 5000
    sentinel:
      nodes: 10.201.12.66:26380,10.201.12.66:26381,10.201.12.66:26382
      master: mymaster
    password: test@123456